EncurtadorURLGoogleAPI/WebSol/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSol.util;

namespace WebSol.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default/Create
        public ActionResult Create()
        {
            var retornoGoogle = new RetornoGoogle();
            ModelState.Clear();

            return View(retornoGoogle);
        }

        // POST: Default/Create
        [HttpGet]
        public ActionResult Create([FromBody]string url)
        {
            try
            {
                var urlCurta = UtilClass.EncurtarURL(url);
                ViewBag.urlCurta = urlCurta;
                var retornoGoogle = new RetornoGoogle
                {
                    id = urlCurta,
                    status = "ok"
                };
                ModelState.Clear();
                return View(retornoGoogle);
            }
            catch
            {
                return View();
            }
        }

    }
}

EncurtadorURLGoogleAPI/WebSol/Views/Default/Create.cshtml
@model WebSol.util.RetornoGoogle
@{
    ViewBag.Title = "Post do Google";
}
<div class="row">
    <div class="col-lg-offset-4 col-lg-5">
        <h2>Criar URL Curta</h2>
        <div class="panel panel-default">
            <div class="panel-body">
                @using (Html.BeginForm("Create", "Default", FormMethod.Get))
                {

          
                    <div class="form-group">
                        <label>Digite a url:</label>
                        <input type="text" class="form-control" placeholder="..." id="url" name="url"/>

                    </div>
                   
                    <button type="submit" class="btn btn-success btn-lg btn-lg">Enviar</button>
          
                }
        
               
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Nova URL:</h3>

                <a href="@Model.id" target="_blank">
                    <h3>@Model.id</h3>
                </a>
            </div>
        </div>
    </div>
</div>
@*<script type="text/javascript">
    window.location.reload();
</script>*@